  
spring:
  datasource:
    username: sysdba
    password: masterkey
    url: jdbc:mysql://192.168.15.164:3306/loja
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MariaDBDialect
